from dotenv import load_dotenv
import os
import requests
import json

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
url = "https://api.generativeai.googleapis.com/v1beta2/models/gemini-1.5:generateText"

headers = {
    "Authorization": f"Bearer {GEMINI_API_KEY}",
    "Content-Type": "application/json",
}

def generate_study_guide_and_calendar(text):
    payload = {
        "prompt": f"""
    You are an academic assistant. Given the following lecture content, do two things:
    1. Generate a concise study guide.
    2. Generate a study calendar for one week.

    Lecture content:
    {text}
    """,
        "temperature": 0.7,
        "max_output_tokens": 1000
    }
    response = requests.post(url, headers=headers, data=json.dumps(payload))
    data = response.json()

    study_output = data['candidates'][0]['content']
    return study_output

def generate_teach(study_output, max_tokens=1000, temperature=0.7):
    """
    Generate a teaching module and quiz based on the study guide and calendar.
    
    Parameters:
    - study_output (str): The text output from the study guide & calendar function.
    - max_tokens (int): Maximum tokens for the API response.
    - temperature (float): Controls creativity of the output.
    
    Returns:
    - str: Teaching module + quiz generated by Gemini API.
    """
    payload = {
        "prompt": f"""
You are a teaching assistant. Based on the following study guide and calendar, create:
1. A teaching module explaining the key concepts in a student-friendly way.
2. A 5-question quiz to test understanding.

Study Output:
{study_output}
""",
        "temperature": temperature,
        "max_output_tokens": max_tokens
    }

    response = requests.post(url, headers=headers, data=json.dumps(payload))
    
    if response.status_code != 200:
        raise Exception(f"API Error: {response.status_code} {response.text}")

    data = response.json()
    teach_output = data['candidates'][0]['content']
    return teach_output

def generate_quiz(source_text, num_questions=5, max_tokens=500, temperature=0.7):
    """
    Generate a quiz based on lecture content or a study guide.

    Parameters:
    - source_text (str): The text to base the quiz on (lecture or study guide).
    - num_questions (int): Number of quiz questions to generate.
    - max_tokens (int): Maximum tokens for the API response.
    - temperature (float): Creativity of the output.

    Returns:
    - str: Quiz generated by Gemini API.
    """
    payload = {
        "prompt": f"""
You are a teaching assistant. Based on the following content, generate a quiz with {num_questions} questions.
Make questions clear and test understanding of the key concepts.

Content:
{source_text}
""",
        "temperature": temperature,
        "max_output_tokens": max_tokens
    }

    response = requests.post(url, headers=headers, data=json.dumps(payload))
    
    if response.status_code != 200:
        raise Exception(f"API Error: {response.status_code} {response.text}")

    data = response.json()
    quiz_output = data['candidates'][0]['content']
    return quiz_output

